_target_: cg_bg.flow.optimizer.get_lr_optimizer
epochs: ${epochs}
num_samples: ${num_samples}
batch_size: ${batch_size}
learning_rate: 0.0003
min_learning_rate: 0.00001
clip: 1000.0
schedule: cosine
weight_decay: 0.00001
