_target_: cg_bg.models.graph_transformer.GraphTransformer
t0: 0.0
t1: 1.0
rescale_time: false
clip_time: false
hidden_nf: 128
feature_embedding_dim: 16
max_z:
  - ${n_nodes}
n_layers: 3
use_intrinsic_coords: true
use_abs_coords: true
use_distances: true
dropout: 0.0
